### ISSUE TITLE
Support a 4k touch screen

### ISSUE THREAD

**Issue by ramyhq** [abdelfatah-ashour/Dell-Precision-5530-OpenCore-EFI-Ventura#1]
hi,
I have this model, can you tell us 
1- What is not working? specially (sleep/wake & 4k touch screen)
2- Does this EFI support a 4k touch screen?

I wish you wonderful day

**Comment by abdelfatah-ashour** [comment]
I have model without touch screen and i used the last version for Ventura 13.5.1. Working 100%
Like:
- USB and Type-c transform data
- Functions built in Mac and syncing with iPhone mobile
- keyboard backlight
- wifi and Bluetooth (100%)
- brightness

No external GPU and disabled (Nvidia p1000 4g) not big deal with me

*** But when you plug in headphones the mic built in work only.

**Comment by ramyhq** [comment]
First, I want to thank you for your reply.
Second, you are the best man in EARTH if you do me this favor ^_^

Can you do Geekbench 6 and share with me the results? 
That would be a great favor for me

**Comment by ramyhq** [comment]
you didn't respond to me?!

**Comment by abdelfatah-ashour** [comment]
![Screenshot 2023-09-28 at 10 16 29 PM](https://github.com/abdelfatah-ashour/Dell-Precision-5530-OpenCore-EFI-Ventura/assets/57315543/67ef524c-a38a-4ce6-92d5-74044a7b289a)

via GeekBench 6

**Comment by ramyhq** [comment]
Thank you so much
